package com.simplyrugby.domain;

import java.util.Date;

/**
 * Represents a report generated by the system.
 */
public class Report {
    private int reportId;
    private String title;
    private String content;
    private Date generatedDate;
    private String generatedBy;
    private String reportType;
    
    /**
     * Default constructor
     */
    public Report() {
        this.generatedDate = new Date();
    }
    
    /**
     * Constructor with all fields
     */
    public Report(int reportId, String title, String content, Date generatedDate, 
                 String generatedBy, String reportType) {
        this.reportId = reportId;
        this.title = title;
        this.content = content;
        this.generatedDate = generatedDate != null ? generatedDate : new Date();
        this.generatedBy = generatedBy;
        this.reportType = reportType;
    }
    
    // Getters and Setters
    
    public int getReportId() {
        return reportId;
    }
    
    public void setReportId(int reportId) {
        this.reportId = reportId;
    }
    
    public String getTitle() {
        return title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getContent() {
        return content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    public Date getGeneratedDate() {
        return generatedDate;
    }
    
    public void setGeneratedDate(Date generatedDate) {
        this.generatedDate = generatedDate;
    }
    
    public String getGeneratedBy() {
        return generatedBy;
    }
    
    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }
    
    public String getReportType() {
        return reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    
    /**
     * Gets a formatted version of the generation date
     * 
     * @return The formatted date
     */
    public String getFormattedDate() {
        if (generatedDate == null) {
            return "Unknown";
        }
        
        return new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(generatedDate);
    }
    
    @Override
    public String toString() {
        return "Report{" + 
               "reportId=" + reportId + 
               ", title='" + title + '\'' + 
               ", generatedDate=" + getFormattedDate() + 
               ", generatedBy='" + generatedBy + '\'' + 
               ", reportType='" + reportType + '\'' + 
               '}';
    }
}